/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.candidatedb.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * HR对候选人备注信息信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CandidateRemark implements Serializable {

    private static final long serialVersionUID = -1313420650;

    private Integer   id;
    private Integer   hraccountId;
    private Integer   wxuserId;
    private Integer   gender;
    private String    age;
    private String    mobile;
    private String    email;
    private String    currentCompany;
    private String    currentPosition;
    private String    education;
    private String    degree;
    private Timestamp graduateAt;
    private Byte      isStar;
    private String    remark;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   status;
    private String    name;
    private Integer   userId;

    public CandidateRemark() {}

    public CandidateRemark(CandidateRemark value) {
        this.id = value.id;
        this.hraccountId = value.hraccountId;
        this.wxuserId = value.wxuserId;
        this.gender = value.gender;
        this.age = value.age;
        this.mobile = value.mobile;
        this.email = value.email;
        this.currentCompany = value.currentCompany;
        this.currentPosition = value.currentPosition;
        this.education = value.education;
        this.degree = value.degree;
        this.graduateAt = value.graduateAt;
        this.isStar = value.isStar;
        this.remark = value.remark;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.status = value.status;
        this.name = value.name;
        this.userId = value.userId;
    }

    public CandidateRemark(
        Integer   id,
        Integer   hraccountId,
        Integer   wxuserId,
        Integer   gender,
        String    age,
        String    mobile,
        String    email,
        String    currentCompany,
        String    currentPosition,
        String    education,
        String    degree,
        Timestamp graduateAt,
        Byte      isStar,
        String    remark,
        Timestamp createTime,
        Timestamp updateTime,
        Integer   status,
        String    name,
        Integer   userId
    ) {
        this.id = id;
        this.hraccountId = hraccountId;
        this.wxuserId = wxuserId;
        this.gender = gender;
        this.age = age;
        this.mobile = mobile;
        this.email = email;
        this.currentCompany = currentCompany;
        this.currentPosition = currentPosition;
        this.education = education;
        this.degree = degree;
        this.graduateAt = graduateAt;
        this.isStar = isStar;
        this.remark = remark;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
        this.name = name;
        this.userId = userId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getHraccountId() {
        return this.hraccountId;
    }

    public void setHraccountId(Integer hraccountId) {
        this.hraccountId = hraccountId;
    }

    public Integer getWxuserId() {
        return this.wxuserId;
    }

    public void setWxuserId(Integer wxuserId) {
        this.wxuserId = wxuserId;
    }

    public Integer getGender() {
        return this.gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public String getAge() {
        return this.age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCurrentCompany() {
        return this.currentCompany;
    }

    public void setCurrentCompany(String currentCompany) {
        this.currentCompany = currentCompany;
    }

    public String getCurrentPosition() {
        return this.currentPosition;
    }

    public void setCurrentPosition(String currentPosition) {
        this.currentPosition = currentPosition;
    }

    public String getEducation() {
        return this.education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getDegree() {
        return this.degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public Timestamp getGraduateAt() {
        return this.graduateAt;
    }

    public void setGraduateAt(Timestamp graduateAt) {
        this.graduateAt = graduateAt;
    }

    public Byte getIsStar() {
        return this.isStar;
    }

    public void setIsStar(Byte isStar) {
        this.isStar = isStar;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CandidateRemark (");

        sb.append(id);
        sb.append(", ").append(hraccountId);
        sb.append(", ").append(wxuserId);
        sb.append(", ").append(gender);
        sb.append(", ").append(age);
        sb.append(", ").append(mobile);
        sb.append(", ").append(email);
        sb.append(", ").append(currentCompany);
        sb.append(", ").append(currentPosition);
        sb.append(", ").append(education);
        sb.append(", ").append(degree);
        sb.append(", ").append(graduateAt);
        sb.append(", ").append(isStar);
        sb.append(", ").append(remark);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(status);
        sb.append(", ").append(name);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
