/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.malldb.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 商品信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MallGoodsInfo implements Serializable {

    private static final long serialVersionUID = -550366518;

    private Integer   id;
    private Integer   companyId;
    private String    title;
    private String    picUrl;
    private Integer   credit;
    private Integer   stock;
    private Integer   exchangeNum;
    private Integer   exchangeOrder;
    private String    detail;
    private Byte      state;
    private String    rule;
    private Timestamp createTime;
    private Timestamp updateTime;

    public MallGoodsInfo() {}

    public MallGoodsInfo(MallGoodsInfo value) {
        this.id = value.id;
        this.companyId = value.companyId;
        this.title = value.title;
        this.picUrl = value.picUrl;
        this.credit = value.credit;
        this.stock = value.stock;
        this.exchangeNum = value.exchangeNum;
        this.exchangeOrder = value.exchangeOrder;
        this.detail = value.detail;
        this.state = value.state;
        this.rule = value.rule;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public MallGoodsInfo(
        Integer   id,
        Integer   companyId,
        String    title,
        String    picUrl,
        Integer   credit,
        Integer   stock,
        Integer   exchangeNum,
        Integer   exchangeOrder,
        String    detail,
        Byte      state,
        String    rule,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.companyId = companyId;
        this.title = title;
        this.picUrl = picUrl;
        this.credit = credit;
        this.stock = stock;
        this.exchangeNum = exchangeNum;
        this.exchangeOrder = exchangeOrder;
        this.detail = detail;
        this.state = state;
        this.rule = rule;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getPicUrl() {
        return this.picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public Integer getCredit() {
        return this.credit;
    }

    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    public Integer getStock() {
        return this.stock;
    }

    public void setStock(Integer stock) {
        this.stock = stock;
    }

    public Integer getExchangeNum() {
        return this.exchangeNum;
    }

    public void setExchangeNum(Integer exchangeNum) {
        this.exchangeNum = exchangeNum;
    }

    public Integer getExchangeOrder() {
        return this.exchangeOrder;
    }

    public void setExchangeOrder(Integer exchangeOrder) {
        this.exchangeOrder = exchangeOrder;
    }

    public String getDetail() {
        return this.detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Byte getState() {
        return this.state;
    }

    public void setState(Byte state) {
        this.state = state;
    }

    public String getRule() {
        return this.rule;
    }

    public void setRule(String rule) {
        this.rule = rule;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MallGoodsInfo (");

        sb.append(id);
        sb.append(", ").append(companyId);
        sb.append(", ").append(title);
        sb.append(", ").append(picUrl);
        sb.append(", ").append(credit);
        sb.append(", ").append(stock);
        sb.append(", ").append(exchangeNum);
        sb.append(", ").append(exchangeOrder);
        sb.append(", ").append(detail);
        sb.append(", ").append(state);
        sb.append(", ").append(rule);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
