/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.profiledb.tables.records;


import com.moseeker.baseorm.db.profiledb.tables.ProfileImport;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户profile导入记录信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileImportRecord extends UpdatableRecordImpl<ProfileImportRecord> implements Record9<Integer, Byte, Timestamp, String, String, String, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1309528204;

    /**
     * Setter for <code>profiledb.profile_import.profile_id</code>. profile.id
     */
    public void setProfileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.profile_id</code>. profile.id
     */
    public Integer getProfileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>profiledb.profile_import.source</code>. 来源, 0:无法识别 1:51Job 2:Liepin 3:zhilian 4:linkedin
     */
    public void setSource(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.source</code>. 来源, 0:无法识别 1:51Job 2:Liepin 3:zhilian 4:linkedin
     */
    public Byte getSource() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>profiledb.profile_import.last_update_time</code>. 导入简历的最后修改时间
     */
    public void setLastUpdateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.last_update_time</code>. 导入简历的最后修改时间
     */
    public Timestamp getLastUpdateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>profiledb.profile_import.account_id</code>. 他系统的用户ID
     */
    public void setAccountId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.account_id</code>. 他系统的用户ID
     */
    public String getAccountId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>profiledb.profile_import.resume_id</code>. 他系统的简历ID
     */
    public void setResumeId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.resume_id</code>. 他系统的简历ID
     */
    public String getResumeId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>profiledb.profile_import.user_name</code>. 他系统的登陆用户名
     */
    public void setUserName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.user_name</code>. 他系统的登陆用户名
     */
    public String getUserName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>profiledb.profile_import.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>profiledb.profile_import.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>profiledb.profile_import.data</code>. 导入数据
     */
    public void setData(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>profiledb.profile_import.data</code>. 导入数据
     */
    public String getData() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Byte, Timestamp, String, String, String, Timestamp, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Byte, Timestamp, String, String, String, Timestamp, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProfileImport.PROFILE_IMPORT.PROFILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return ProfileImport.PROFILE_IMPORT.SOURCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ProfileImport.PROFILE_IMPORT.LAST_UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProfileImport.PROFILE_IMPORT.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ProfileImport.PROFILE_IMPORT.RESUME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ProfileImport.PROFILE_IMPORT.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ProfileImport.PROFILE_IMPORT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return ProfileImport.PROFILE_IMPORT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return ProfileImport.PROFILE_IMPORT.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getSource();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getLastUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getResumeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value1(Integer value) {
        setProfileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value2(Byte value) {
        setSource(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value3(Timestamp value) {
        setLastUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value4(String value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value5(String value) {
        setResumeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value6(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord value9(String value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfileImportRecord values(Integer value1, Byte value2, Timestamp value3, String value4, String value5, String value6, Timestamp value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfileImportRecord
     */
    public ProfileImportRecord() {
        super(ProfileImport.PROFILE_IMPORT);
    }

    /**
     * Create a detached, initialised ProfileImportRecord
     */
    public ProfileImportRecord(Integer profileId, Byte source, Timestamp lastUpdateTime, String accountId, String resumeId, String userName, Timestamp createTime, Timestamp updateTime, String data) {
        super(ProfileImport.PROFILE_IMPORT);

        set(0, profileId);
        set(1, source);
        set(2, lastUpdateTime);
        set(3, accountId);
        set(4, resumeId);
        set(5, userName);
        set(6, createTime);
        set(7, updateTime);
        set(8, data);
    }
}
