package com.moseeker.common.constants;

public enum KeyIdentifier {
	DEFAULT, LOG, LOG_INPROGRESS, SMS_SIGNUP, SMS_PWD_FORGOT, DICT_CITY, SMS_CHANGEMOBILE_CODE, SMS_RESETMOBILE_CODE, DICT_COLLEGE, APPLICATION_COUNT_CHECK, HR_SMS_SIGNUP, MQ_MESSAGE_NOTICE_TEMPLATE, MQ_MESSAGE_NOTICE_TEMPLATE_INPRO, MQ_MESSAGE_EMAIL_BIZ, MQ_MESSAGE_EMAIL_WARNING, WEIXIN_SCANRESULT, NEWSLETTER_HRACCOUNT_READED;
}
