/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.hrdb.tables.records;


import com.moseeker.baseorm.db.hrdb.tables.HrCompanyRecruitProcess;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 公司招聘流程配置表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HrCompanyRecruitProcessRecord extends UpdatableRecordImpl<HrCompanyRecruitProcessRecord> implements Record7<Integer, String, Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 430631938;

    /**
     * Setter for <code>hrdb.hr_company_recruit_process.id</code>. 序列ID
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>hrdb.hr_company_recruit_process.id</code>. 序列ID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hrdb.hr_company_recruit_process.recruit_process_name</code>. 阶段名称(初筛、面试、offer、待入职、已入职)
     */
    public void setRecruitProcessName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hrdb.hr_company_recruit_process.recruit_process_name</code>. 阶段名称(初筛、面试、offer、待入职、已入职)
     */
    public String getRecruitProcessName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hrdb.hr_company_recruit_process.company_id</code>. 公司ID 默认0
     */
    public void setCompanyId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>hrdb.hr_company_recruit_process.company_id</code>. 公司ID 默认0
     */
    public Integer getCompanyId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>hrdb.hr_company_recruit_process.disable</code>. 状态：0 有效  1 无效 2 逻辑删除
     */
    public void setDisable(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>hrdb.hr_company_recruit_process.disable</code>. 状态：0 有效  1 无效 2 逻辑删除
     */
    public Integer getDisable() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>hrdb.hr_company_recruit_process.process_order</code>. 排序
     */
    public void setProcessOrder(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>hrdb.hr_company_recruit_process.process_order</code>. 排序
     */
    public Integer getProcessOrder() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>hrdb.hr_company_recruit_process.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>hrdb.hr_company_recruit_process.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>hrdb.hr_company_recruit_process.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>hrdb.hr_company_recruit_process.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS.RECRUIT_PROCESS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS.DISABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS.PROCESS_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRecruitProcessName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDisable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getProcessOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord value2(String value) {
        setRecruitProcessName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord value3(Integer value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord value4(Integer value) {
        setDisable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord value5(Integer value) {
        setProcessOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrCompanyRecruitProcessRecord values(Integer value1, String value2, Integer value3, Integer value4, Integer value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HrCompanyRecruitProcessRecord
     */
    public HrCompanyRecruitProcessRecord() {
        super(HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS);
    }

    /**
     * Create a detached, initialised HrCompanyRecruitProcessRecord
     */
    public HrCompanyRecruitProcessRecord(Integer id, String recruitProcessName, Integer companyId, Integer disable, Integer processOrder, Timestamp createTime, Timestamp updateTime) {
        super(HrCompanyRecruitProcess.HR_COMPANY_RECRUIT_PROCESS);

        set(0, id);
        set(1, recruitProcessName);
        set(2, companyId);
        set(3, disable);
        set(4, processOrder);
        set(5, createTime);
        set(6, updateTime);
    }
}
