/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.hrdb.tables.records;


import com.moseeker.baseorm.db.hrdb.tables.HrHbTheme;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 红包活动与主题的关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HrHbThemeRecord extends UpdatableRecordImpl<HrHbThemeRecord> implements Record4<Integer, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = 2051656289;

    /**
     * Setter for <code>hrdb.hr_hb_theme.config_id</code>. 红包活动编号
     */
    public void setConfigId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>hrdb.hr_hb_theme.config_id</code>. 红包活动编号
     */
    public Integer getConfigId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>hrdb.hr_hb_theme.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>hrdb.hr_hb_theme.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>hrdb.hr_hb_theme.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>hrdb.hr_hb_theme.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>hrdb.hr_hb_theme.theme_id</code>. 主题编号
     */
    public void setThemeId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>hrdb.hr_hb_theme.theme_id</code>. 主题编号
     */
    public Integer getThemeId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return HrHbTheme.HR_HB_THEME.CONFIG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return HrHbTheme.HR_HB_THEME.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return HrHbTheme.HR_HB_THEME.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return HrHbTheme.HR_HB_THEME.THEME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getConfigId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getThemeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrHbThemeRecord value1(Integer value) {
        setConfigId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrHbThemeRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrHbThemeRecord value3(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrHbThemeRecord value4(Integer value) {
        setThemeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public HrHbThemeRecord values(Integer value1, Timestamp value2, Timestamp value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HrHbThemeRecord
     */
    public HrHbThemeRecord() {
        super(HrHbTheme.HR_HB_THEME);
    }

    /**
     * Create a detached, initialised HrHbThemeRecord
     */
    public HrHbThemeRecord(Integer configId, Timestamp createTime, Timestamp updateTime, Integer themeId) {
        super(HrHbTheme.HR_HB_THEME);

        set(0, configId);
        set(1, createTime);
        set(2, updateTime);
        set(3, themeId);
    }
}
