/**
 * This class is generated by jOOQ
 */
package com.moseeker.baseorm.db.dictdb;


import com.moseeker.baseorm.db.dictdb.tables.DictCity;
import com.moseeker.baseorm.db.dictdb.tables.DictCollege;
import com.moseeker.baseorm.db.dictdb.tables.DictConstant;
import com.moseeker.baseorm.db.dictdb.tables.DictCountry;
import com.moseeker.baseorm.db.dictdb.tables.DictIndustry;
import com.moseeker.baseorm.db.dictdb.tables.DictIndustryType;
import com.moseeker.baseorm.db.dictdb.tables.DictMajor;
import com.moseeker.baseorm.db.dictdb.tables.DictPosition;
import com.moseeker.baseorm.db.dictdb.tables.DictZhilianOccupation;
import com.moseeker.baseorm.db.dictdb.tables.Dict_51jobOccupation;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dictdb extends SchemaImpl {

    private static final long serialVersionUID = -1992811729;

    /**
     * The reference instance of <code>dictdb</code>
     */
    public static final Dictdb DICTDB = new Dictdb();

    /**
     * The table <code>dictdb.dict_51job_occupation</code>.
     */
    public final Dict_51jobOccupation DICT_51JOB_OCCUPATION = com.moseeker.baseorm.db.dictdb.tables.Dict_51jobOccupation.DICT_51JOB_OCCUPATION;

    /**
     * 城市字典表
     */
    public final DictCity DICT_CITY = com.moseeker.baseorm.db.dictdb.tables.DictCity.DICT_CITY;

    /**
     * 学校字典表
     */
    public final DictCollege DICT_COLLEGE = com.moseeker.baseorm.db.dictdb.tables.DictCollege.DICT_COLLEGE;

    /**
     * 常量字典表
     */
    public final DictConstant DICT_CONSTANT = com.moseeker.baseorm.db.dictdb.tables.DictConstant.DICT_CONSTANT;

    /**
     * 城市字典表
     */
    public final DictCountry DICT_COUNTRY = com.moseeker.baseorm.db.dictdb.tables.DictCountry.DICT_COUNTRY;

    /**
     * 行业二级分类字典表
     */
    public final DictIndustry DICT_INDUSTRY = com.moseeker.baseorm.db.dictdb.tables.DictIndustry.DICT_INDUSTRY;

    /**
     * 行业一级分类字典表
     */
    public final DictIndustryType DICT_INDUSTRY_TYPE = com.moseeker.baseorm.db.dictdb.tables.DictIndustryType.DICT_INDUSTRY_TYPE;

    /**
     * 专业字典表
     */
    public final DictMajor DICT_MAJOR = com.moseeker.baseorm.db.dictdb.tables.DictMajor.DICT_MAJOR;

    /**
     * 职能分类字典表
     */
    public final DictPosition DICT_POSITION = com.moseeker.baseorm.db.dictdb.tables.DictPosition.DICT_POSITION;

    /**
     * The table <code>dictdb.dict_zhilian_occupation</code>.
     */
    public final DictZhilianOccupation DICT_ZHILIAN_OCCUPATION = com.moseeker.baseorm.db.dictdb.tables.DictZhilianOccupation.DICT_ZHILIAN_OCCUPATION;

    /**
     * No further instances allowed
     */
    private Dictdb() {
        super("dictdb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Dict_51jobOccupation.DICT_51JOB_OCCUPATION,
            DictCity.DICT_CITY,
            DictCollege.DICT_COLLEGE,
            DictConstant.DICT_CONSTANT,
            DictCountry.DICT_COUNTRY,
            DictIndustry.DICT_INDUSTRY,
            DictIndustryType.DICT_INDUSTRY_TYPE,
            DictMajor.DICT_MAJOR,
            DictPosition.DICT_POSITION,
            DictZhilianOccupation.DICT_ZHILIAN_OCCUPATION);
    }
}
