package com.moseeker.position.constants.position;

public class PositionAsyncConstant {

    public static final String POSITION_BATCH_HANDLE_EXCHANGE = "POSITION_BATCH_HANDLE_EXCHANGE";

    public static final String POSITION_BATCH_HANDLE_REQUEST_ROUTING_KEY = "POSITION_BATCH_HANDLE_REQUEST_ROUTING_KEY";
    public static final String POSITION_BATCH_HANDLE_REQUEST_QUEUE = "POSITION_BATCH_HANDLE_REQUEST_QUEUE";


    public static final String POSITION_BATCH_HANDLE_RESPONSE_ROUTING_KEY = "POSITION_BATCH_HANDLE_RESPONSE_ROUTING_KEY";
    public static final String POSITION_BATCH_HANDLE_RESPONSE_QUEUE = "POSITION_BATCH_HANDLE_RESPONSE_QUEUE";
}
