/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.historydb.tables.daos;


import com.moseeker.baseorm.db.historydb.tables.HistoryHrOperationRecord;
import com.moseeker.baseorm.db.historydb.tables.records.HistoryHrOperationRecordRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 15年的一批hr申请状态操作记录老数据，在进行数据处理时，其中一些数据目前无法处理，暂时移到历史表中，这些数据中包括申请状态是hr操作记录包括1的，
 * 
 * hr申请记录无法梳理出合理的流程的记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoryHrOperationRecordDao extends DAOImpl<HistoryHrOperationRecordRecord, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord, Integer> {

    /**
     * Create a new HistoryHrOperationRecordDao without any configuration
     */
    public HistoryHrOperationRecordDao() {
        super(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord.class);
    }

    /**
     * Create a new HistoryHrOperationRecordDao with an attached configuration
     */
    public HistoryHrOperationRecordDao(Configuration configuration) {
        super(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord> fetchById(Integer... values) {
        return fetch(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord fetchOneById(Integer value) {
        return fetchOne(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.ID, value);
    }

    /**
     * Fetch records that have <code>admin_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord> fetchByAdminId(Long... values) {
        return fetch(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.ADMIN_ID, values);
    }

    /**
     * Fetch records that have <code>company_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord> fetchByCompanyId(Long... values) {
        return fetch(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.COMPANY_ID, values);
    }

    /**
     * Fetch records that have <code>app_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord> fetchByAppId(Long... values) {
        return fetch(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.APP_ID, values);
    }

    /**
     * Fetch records that have <code>status_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord> fetchByStatusId(Long... values) {
        return fetch(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.STATUS_ID, values);
    }

    /**
     * Fetch records that have <code>opt_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord> fetchByOptTime(Timestamp... values) {
        return fetch(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.OPT_TIME, values);
    }

    /**
     * Fetch records that have <code>operate_tpl_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrOperationRecord> fetchByOperateTplId(Integer... values) {
        return fetch(HistoryHrOperationRecord.HISTORY_HR_OPERATION_RECORD.OPERATE_TPL_ID, values);
    }
}
