/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.historydb.tables.daos;


import com.moseeker.baseorm.db.historydb.tables.HistoryDictCountry;
import com.moseeker.baseorm.db.historydb.tables.records.HistoryDictCountryRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 城市字典表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoryDictCountryDao extends DAOImpl<HistoryDictCountryRecord, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry, Integer> {

    /**
     * Create a new HistoryDictCountryDao without any configuration
     */
    public HistoryDictCountryDao() {
        super(HistoryDictCountry.HISTORY_DICT_COUNTRY, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry.class);
    }

    /**
     * Create a new HistoryDictCountryDao with an attached configuration
     */
    public HistoryDictCountryDao(Configuration configuration) {
        super(HistoryDictCountry.HISTORY_DICT_COUNTRY, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchById(Integer... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry fetchOneById(Integer value) {
        return fetchOne(HistoryDictCountry.HISTORY_DICT_COUNTRY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByName(String... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.NAME, values);
    }

    /**
     * Fetch records that have <code>ename IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByEname(String... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.ENAME, values);
    }

    /**
     * Fetch records that have <code>iso_code_2 IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByIsoCode_2(String... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.ISO_CODE_2, values);
    }

    /**
     * Fetch records that have <code>iso_code_3 IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByIsoCode_3(String... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.ISO_CODE_3, values);
    }

    /**
     * Fetch records that have <code>code IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByCode(String... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.CODE, values);
    }

    /**
     * Fetch records that have <code>sms_enabled IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchBySmsEnabled(Byte... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.SMS_ENABLED, values);
    }

    /**
     * Fetch records that have <code>icon_class IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByIconClass(String... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.ICON_CLASS, values);
    }

    /**
     * Fetch records that have <code>hot_country IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByHotCountry(Byte... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.HOT_COUNTRY, values);
    }

    /**
     * Fetch records that have <code>continent_code IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByContinentCode(Integer... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.CONTINENT_CODE, values);
    }

    /**
     * Fetch records that have <code>priority IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryDictCountry> fetchByPriority(Short... values) {
        return fetch(HistoryDictCountry.HISTORY_DICT_COUNTRY.PRIORITY, values);
    }
}
