/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.historydb.tables.daos;


import com.moseeker.baseorm.db.historydb.tables.HistoryHrChildCompany;
import com.moseeker.baseorm.db.historydb.tables.records.HistoryHrChildCompanyRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 子公司表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HistoryHrChildCompanyDao extends DAOImpl<HistoryHrChildCompanyRecord, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany, Integer> {

    /**
     * Create a new HistoryHrChildCompanyDao without any configuration
     */
    public HistoryHrChildCompanyDao() {
        super(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany.class);
    }

    /**
     * Create a new HistoryHrChildCompanyDao with an attached configuration
     */
    public HistoryHrChildCompanyDao(Configuration configuration) {
        super(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY, com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchById(Integer... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany fetchOneById(Integer value) {
        return fetchOne(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByName(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.NAME, values);
    }

    /**
     * Fetch records that have <code>ename IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByEname(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.ENAME, values);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByStatus(Byte... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.STATUS, values);
    }

    /**
     * Fetch records that have <code>CEO IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByCeo(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.CEO, values);
    }

    /**
     * Fetch records that have <code>introduction IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByIntroduction(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.INTRODUCTION, values);
    }

    /**
     * Fetch records that have <code>scale IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByScale(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.SCALE, values);
    }

    /**
     * Fetch records that have <code>province IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByProvince(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.PROVINCE, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByCity(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.CITY, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByAddress(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.ADDRESS, values);
    }

    /**
     * Fetch records that have <code>property IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByProperty(Byte... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.PROPERTY, values);
    }

    /**
     * Fetch records that have <code>business IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByBusiness(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.BUSINESS, values);
    }

    /**
     * Fetch records that have <code>establish_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByEstablishTime(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.ESTABLISH_TIME, values);
    }

    /**
     * Fetch records that have <code>parent_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByParentId(Integer... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.PARENT_ID, values);
    }

    /**
     * Fetch records that have <code>homepage IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByHomepage(String... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.HOMEPAGE, values);
    }

    /**
     * Fetch records that have <code>company_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.historydb.tables.pojos.HistoryHrChildCompany> fetchByCompanyId(Integer... values) {
        return fetch(HistoryHrChildCompany.HISTORY_HR_CHILD_COMPANY.COMPANY_ID, values);
    }
}
