/**
 * This class is generated by jOOQ
 */
package com.moseeker.db.userdb.tables.records;


import com.moseeker.db.userdb.tables.SysUserPcresumeMonitor;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户在线简历状态监控表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SysUserPcresumeMonitorRecord extends UpdatableRecordImpl<SysUserPcresumeMonitorRecord> implements Record10<Integer, Long, String, Byte, String, Byte, Byte, Long, Timestamp, Timestamp> {

	private static final long serialVersionUID = -226764399;

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.sysuser_id</code>. sysuser.id
	 */
	public void setSysuserId(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.sysuser_id</code>. sysuser.id
	 */
	public Long getSysuserId() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.unionid</code>. 微信用户的unionid
	 */
	public void setUnionid(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.unionid</code>. 微信用户的unionid
	 */
	public String getUnionid() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.errcode</code>. 处理状态0：成功1：待处理2：失败
	 */
	public void setErrcode(Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.errcode</code>. 处理状态0：成功1：待处理2：失败
	 */
	public Byte getErrcode() {
		return (Byte) getValue(3);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.errmsg</code>. 处理状态提示信息
	 */
	public void setErrmsg(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.errmsg</code>. 处理状态提示信息
	 */
	public String getErrmsg() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.type</code>. 监控分类 0：无效分类，1：pc扫码登录 2：pc简历填写
	 */
	public void setType(Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.type</code>. 监控分类 0：无效分类，1：pc扫码登录 2：pc简历填写
	 */
	public Byte getType() {
		return (Byte) getValue(5);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.disable</code>. 是否失效，0：有效1：失效
	 */
	public void setDisable(Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.disable</code>. 是否失效，0：有效1：失效
	 */
	public Byte getDisable() {
		return (Byte) getValue(6);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.monitor_start_time</code>. 创建霎间
	 */
	public void setMonitorStartTime(Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.monitor_start_time</code>. 创建霎间
	 */
	public Long getMonitorStartTime() {
		return (Long) getValue(7);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.create_time</code>. 创建时间
	 */
	public void setCreateTime(Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.create_time</code>. 创建时间
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>userDB.sys_user_pcresume_monitor.update_time</code>. 修改时间
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>userDB.sys_user_pcresume_monitor.update_time</code>. 修改时间
	 */
	public Timestamp getUpdateTime() {
		return (Timestamp) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Long, String, Byte, String, Byte, Byte, Long, Timestamp, Timestamp> fieldsRow() {
		return (Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row10<Integer, Long, String, Byte, String, Byte, Byte, Long, Timestamp, Timestamp> valuesRow() {
		return (Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field2() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.SYSUSER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.UNIONID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field4() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.ERRCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.ERRMSG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field6() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Byte> field7() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.DISABLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field8() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.MONITOR_START_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field9() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field10() {
		return SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value2() {
		return getSysuserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getUnionid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value4() {
		return getErrcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getErrmsg();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value6() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Byte value7() {
		return getDisable();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value8() {
		return getMonitorStartTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value9() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value10() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value2(Long value) {
		setSysuserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value3(String value) {
		setUnionid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value4(Byte value) {
		setErrcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value5(String value) {
		setErrmsg(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value6(Byte value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value7(Byte value) {
		setDisable(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value8(Long value) {
		setMonitorStartTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value9(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord value10(Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SysUserPcresumeMonitorRecord values(Integer value1, Long value2, String value3, Byte value4, String value5, Byte value6, Byte value7, Long value8, Timestamp value9, Timestamp value10) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SysUserPcresumeMonitorRecord
	 */
	public SysUserPcresumeMonitorRecord() {
		super(SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR);
	}

	/**
	 * Create a detached, initialised SysUserPcresumeMonitorRecord
	 */
	public SysUserPcresumeMonitorRecord(Integer id, Long sysuserId, String unionid, Byte errcode, String errmsg, Byte type, Byte disable, Long monitorStartTime, Timestamp createTime, Timestamp updateTime) {
		super(SysUserPcresumeMonitor.SYS_USER_PCRESUME_MONITOR);

		setValue(0, id);
		setValue(1, sysuserId);
		setValue(2, unionid);
		setValue(3, errcode);
		setValue(4, errmsg);
		setValue(5, type);
		setValue(6, disable);
		setValue(7, monitorStartTime);
		setValue(8, createTime);
		setValue(9, updateTime);
	}
}
