/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.dictdb.tables.records;


import com.moseeker.baseorm.db.dictdb.tables.DictCityPostcode;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictCityPostcodeRecord extends UpdatableRecordImpl<DictCityPostcodeRecord> implements Record6<Integer, String, String, String, String, String> {

    private static final long serialVersionUID = 758158555;

    /**
     * Setter for <code>dictdb.dict_city_postcode.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>dictdb.dict_city_postcode.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>dictdb.dict_city_postcode.postcode</code>. 邮编
     */
    public void setPostcode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>dictdb.dict_city_postcode.postcode</code>. 邮编
     */
    public String getPostcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>dictdb.dict_city_postcode.province</code>. 省份
     */
    public void setProvince(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>dictdb.dict_city_postcode.province</code>. 省份
     */
    public String getProvince() {
        return (String) get(2);
    }

    /**
     * Setter for <code>dictdb.dict_city_postcode.city</code>. 城市
     */
    public void setCity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>dictdb.dict_city_postcode.city</code>. 城市
     */
    public String getCity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>dictdb.dict_city_postcode.district</code>. 地区或区县
     */
    public void setDistrict(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>dictdb.dict_city_postcode.district</code>. 地区或区县
     */
    public String getDistrict() {
        return (String) get(4);
    }

    /**
     * Setter for <code>dictdb.dict_city_postcode.code</code>. 行政区号
     */
    public void setCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>dictdb.dict_city_postcode.code</code>. 行政区号
     */
    public String getCode() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DictCityPostcode.DICT_CITY_POSTCODE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DictCityPostcode.DICT_CITY_POSTCODE.POSTCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DictCityPostcode.DICT_CITY_POSTCODE.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DictCityPostcode.DICT_CITY_POSTCODE.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DictCityPostcode.DICT_CITY_POSTCODE.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DictCityPostcode.DICT_CITY_POSTCODE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPostcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictCityPostcodeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictCityPostcodeRecord value2(String value) {
        setPostcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictCityPostcodeRecord value3(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictCityPostcodeRecord value4(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictCityPostcodeRecord value5(String value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictCityPostcodeRecord value6(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictCityPostcodeRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DictCityPostcodeRecord
     */
    public DictCityPostcodeRecord() {
        super(DictCityPostcode.DICT_CITY_POSTCODE);
    }

    /**
     * Create a detached, initialised DictCityPostcodeRecord
     */
    public DictCityPostcodeRecord(Integer id, String postcode, String province, String city, String district, String code) {
        super(DictCityPostcode.DICT_CITY_POSTCODE);

        set(0, id);
        set(1, postcode);
        set(2, province);
        set(3, city);
        set(4, district);
        set(5, code);
    }
}
