/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.malldb.tables.records;


import com.moseeker.baseorm.db.malldb.tables.MallMailAddress;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 邮寄地址信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MallMailAddressRecord extends UpdatableRecordImpl<MallMailAddressRecord> implements Record10<Integer, Integer, String, String, Integer, Integer, Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1824744446;

    /**
     * Setter for <code>malldb.mall_mail_address.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.user_id</code>. 用户id,user_user.id
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.user_id</code>. 用户id,user_user.id
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.addressee</code>. 收件人姓名
     */
    public void setAddressee(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.addressee</code>. 收件人姓名
     */
    public String getAddressee() {
        return (String) get(2);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.mobile</code>. 收件人手机号
     */
    public void setMobile(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.mobile</code>. 收件人手机号
     */
    public String getMobile() {
        return (String) get(3);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.province</code>. 收件地址所属省份，dict_city.code
     */
    public void setProvince(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.province</code>. 收件地址所属省份，dict_city.code
     */
    public Integer getProvince() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.city</code>. 收件地址所属城市，dict_city.code
     */
    public void setCity(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.city</code>. 收件地址所属城市，dict_city.code
     */
    public Integer getCity() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.region</code>. 收件地址所属城市区，dict_city.code
     */
    public void setRegion(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.region</code>. 收件地址所属城市区，dict_city.code
     */
    public Integer getRegion() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.address</code>. 收件详细地址
     */
    public void setAddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.address</code>. 收件详细地址
     */
    public String getAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>malldb.mall_mail_address.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>malldb.mall_mail_address.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, Integer, Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, String, String, Integer, Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MallMailAddress.MALL_MAIL_ADDRESS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MallMailAddress.MALL_MAIL_ADDRESS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MallMailAddress.MALL_MAIL_ADDRESS.ADDRESSEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MallMailAddress.MALL_MAIL_ADDRESS.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MallMailAddress.MALL_MAIL_ADDRESS.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return MallMailAddress.MALL_MAIL_ADDRESS.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return MallMailAddress.MALL_MAIL_ADDRESS.REGION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MallMailAddress.MALL_MAIL_ADDRESS.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return MallMailAddress.MALL_MAIL_ADDRESS.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return MallMailAddress.MALL_MAIL_ADDRESS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddressee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getRegion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value3(String value) {
        setAddressee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value4(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value5(Integer value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value6(Integer value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value7(Integer value) {
        setRegion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value8(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord value10(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MallMailAddressRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Integer value7, String value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MallMailAddressRecord
     */
    public MallMailAddressRecord() {
        super(MallMailAddress.MALL_MAIL_ADDRESS);
    }

    /**
     * Create a detached, initialised MallMailAddressRecord
     */
    public MallMailAddressRecord(Integer id, Integer userId, String addressee, String mobile, Integer province, Integer city, Integer region, String address, Timestamp createTime, Timestamp updateTime) {
        super(MallMailAddress.MALL_MAIL_ADDRESS);

        set(0, id);
        set(1, userId);
        set(2, addressee);
        set(3, mobile);
        set(4, province);
        set(5, city);
        set(6, region);
        set(7, address);
        set(8, createTime);
        set(9, updateTime);
    }
}
