/**
 * This class is generated by jOOQ
 */
package com.moseeker.db.configdb.tables.records;


import com.moseeker.db.configdb.tables.CacheconfigRediskey;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * redis缓存配置表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CacheconfigRediskeyRecord extends UpdatableRecordImpl<CacheconfigRediskeyRecord> implements Record8<Integer, Integer, String, String, String, Integer, String, Timestamp> {

	private static final long serialVersionUID = -447063851;

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.project_appid</code>. 项目id
	 */
	public void setProjectAppid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.project_appid</code>. 项目id
	 */
	public Integer getProjectAppid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.key_identifier</code>. 标识符， 大写英文字母
	 */
	public void setKeyIdentifier(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.key_identifier</code>. 标识符， 大写英文字母
	 */
	public String getKeyIdentifier() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.pattern</code>. 格式， 形如 ip_limit_%s
	 */
	public void setPattern(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.pattern</code>. 格式， 形如 ip_limit_%s
	 */
	public String getPattern() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.json_extraparams</code>. 额外参数， 如{'maxPerHour':100}
	 */
	public void setJsonExtraparams(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.json_extraparams</code>. 额外参数， 如{'maxPerHour':100}
	 */
	public String getJsonExtraparams() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.ttl</code>. 生存时间， 单位秒
	 */
	public void setTtl(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.ttl</code>. 生存时间， 单位秒
	 */
	public Integer getTtl() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.desc</code>. 备注， 包含json_extraparams的解释
	 */
	public void setDesc(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.desc</code>. 备注， 包含json_extraparams的解释
	 */
	public String getDesc() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>configDB.cacheconfig_rediskey.create_time</code>.
	 */
	public void setCreateTime(Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>configDB.cacheconfig_rediskey.create_time</code>.
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, String, Integer, String, Timestamp> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, String, Integer, String, Timestamp> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.PROJECT_APPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.KEY_IDENTIFIER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.PATTERN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.JSON_EXTRAPARAMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.TTL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.DESC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return CacheconfigRediskey.CACHECONFIG_REDISKEY.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getProjectAppid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getKeyIdentifier();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getPattern();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getJsonExtraparams();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getTtl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getDesc();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value2(Integer value) {
		setProjectAppid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value3(String value) {
		setKeyIdentifier(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value4(String value) {
		setPattern(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value5(String value) {
		setJsonExtraparams(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value6(Integer value) {
		setTtl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value7(String value) {
		setDesc(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord value8(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CacheconfigRediskeyRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Integer value6, String value7, Timestamp value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CacheconfigRediskeyRecord
	 */
	public CacheconfigRediskeyRecord() {
		super(CacheconfigRediskey.CACHECONFIG_REDISKEY);
	}

	/**
	 * Create a detached, initialised CacheconfigRediskeyRecord
	 */
	public CacheconfigRediskeyRecord(Integer id, Integer projectAppid, String keyIdentifier, String pattern, String jsonExtraparams, Integer ttl, String desc, Timestamp createTime) {
		super(CacheconfigRediskey.CACHECONFIG_REDISKEY);

		setValue(0, id);
		setValue(1, projectAppid);
		setValue(2, keyIdentifier);
		setValue(3, pattern);
		setValue(4, jsonExtraparams);
		setValue(5, ttl);
		setValue(6, desc);
		setValue(7, createTime);
	}
}
