/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.hrdb.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 面试反馈结果
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HrInterviewFeedbackResultAnswerSheet implements Serializable {

    private static final long serialVersionUID = -576224001;

    private Integer   id;
    private Integer   interviewerId;
    private Integer   applierId;
    private Integer   applicationId;
    private Integer   interviewConcreteId;
    private Integer   interviewTemplateId;
    private Integer   passed;
    private String    evaluation;
    private Integer   disable;
    private Timestamp createTime;
    private Timestamp updateTime;

    public HrInterviewFeedbackResultAnswerSheet() {}

    public HrInterviewFeedbackResultAnswerSheet(HrInterviewFeedbackResultAnswerSheet value) {
        this.id = value.id;
        this.interviewerId = value.interviewerId;
        this.applierId = value.applierId;
        this.applicationId = value.applicationId;
        this.interviewConcreteId = value.interviewConcreteId;
        this.interviewTemplateId = value.interviewTemplateId;
        this.passed = value.passed;
        this.evaluation = value.evaluation;
        this.disable = value.disable;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public HrInterviewFeedbackResultAnswerSheet(
        Integer   id,
        Integer   interviewerId,
        Integer   applierId,
        Integer   applicationId,
        Integer   interviewConcreteId,
        Integer   interviewTemplateId,
        Integer   passed,
        String    evaluation,
        Integer   disable,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.interviewerId = interviewerId;
        this.applierId = applierId;
        this.applicationId = applicationId;
        this.interviewConcreteId = interviewConcreteId;
        this.interviewTemplateId = interviewTemplateId;
        this.passed = passed;
        this.evaluation = evaluation;
        this.disable = disable;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getInterviewerId() {
        return this.interviewerId;
    }

    public void setInterviewerId(Integer interviewerId) {
        this.interviewerId = interviewerId;
    }

    public Integer getApplierId() {
        return this.applierId;
    }

    public void setApplierId(Integer applierId) {
        this.applierId = applierId;
    }

    public Integer getApplicationId() {
        return this.applicationId;
    }

    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    public Integer getInterviewConcreteId() {
        return this.interviewConcreteId;
    }

    public void setInterviewConcreteId(Integer interviewConcreteId) {
        this.interviewConcreteId = interviewConcreteId;
    }

    public Integer getInterviewTemplateId() {
        return this.interviewTemplateId;
    }

    public void setInterviewTemplateId(Integer interviewTemplateId) {
        this.interviewTemplateId = interviewTemplateId;
    }

    public Integer getPassed() {
        return this.passed;
    }

    public void setPassed(Integer passed) {
        this.passed = passed;
    }

    public String getEvaluation() {
        return this.evaluation;
    }

    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    public Integer getDisable() {
        return this.disable;
    }

    public void setDisable(Integer disable) {
        this.disable = disable;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("HrInterviewFeedbackResultAnswerSheet (");

        sb.append(id);
        sb.append(", ").append(interviewerId);
        sb.append(", ").append(applierId);
        sb.append(", ").append(applicationId);
        sb.append(", ").append(interviewConcreteId);
        sb.append(", ").append(interviewTemplateId);
        sb.append(", ").append(passed);
        sb.append(", ").append(evaluation);
        sb.append(", ").append(disable);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
