/**
 * This class is generated by jOOQ
 */
package com.moseeker.db.profiledb.tables.records;


import com.moseeker.db.profiledb.tables.ProfileBasic;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * 用户profile基础个人信息表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileBasicRecord extends UpdatableRecordImpl<ProfileBasicRecord> implements Record12<UInteger, String, UByte, Integer, Integer, Date, String, String, String, String, Timestamp, Timestamp> {

	private static final long serialVersionUID = 1739196138;

	/**
	 * Setter for <code>profileDB.profile_basic.profile_id</code>. profile.id
	 */
	public void setProfileId(UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.profile_id</code>. profile.id
	 */
	public UInteger getProfileId() {
		return (UInteger) getValue(0);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.name</code>. 姓名
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.name</code>. 姓名
	 */
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.gender</code>. 性别 0:没选择 1:男, 2: 女
	 */
	public void setGender(UByte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.gender</code>. 性别 0:没选择 1:男, 2: 女
	 */
	public UByte getGender() {
		return (UByte) getValue(2);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.nationality</code>. 国籍
	 */
	public void setNationality(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.nationality</code>. 国籍
	 */
	public Integer getNationality() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.location</code>. 现居住地址, 城市字典
	 */
	public void setLocation(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.location</code>. 现居住地址, 城市字典
	 */
	public Integer getLocation() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.birth</code>. 出生年月 yyyy-mm-dd
	 */
	public void setBirth(Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.birth</code>. 出生年月 yyyy-mm-dd
	 */
	public Date getBirth() {
		return (Date) getValue(5);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.weixin</code>. 微信号
	 */
	public void setWeixin(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.weixin</code>. 微信号
	 */
	public String getWeixin() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.qq</code>. QQ号
	 */
	public void setQq(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.qq</code>. QQ号
	 */
	public String getQq() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.motto</code>. 座右铭
	 */
	public void setMotto(String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.motto</code>. 座右铭
	 */
	public String getMotto() {
		return (String) getValue(8);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.self_introduction</code>. 自我介绍
	 */
	public void setSelfIntroduction(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.self_introduction</code>. 自我介绍
	 */
	public String getSelfIntroduction() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.create_time</code>. 创建时间
	 */
	public void setCreateTime(Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.create_time</code>. 创建时间
	 */
	public Timestamp getCreateTime() {
		return (Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>profileDB.profile_basic.update_time</code>. 更新时间
	 */
	public void setUpdateTime(Timestamp value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>profileDB.profile_basic.update_time</code>. 更新时间
	 */
	public Timestamp getUpdateTime() {
		return (Timestamp) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<UInteger> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<UInteger, String, UByte, Integer, Integer, Date, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
		return (Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row12<UInteger, String, UByte, Integer, Integer, Date, String, String, String, String, Timestamp, Timestamp> valuesRow() {
		return (Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UInteger> field1() {
		return ProfileBasic.PROFILE_BASIC.PROFILE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return ProfileBasic.PROFILE_BASIC.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UByte> field3() {
		return ProfileBasic.PROFILE_BASIC.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return ProfileBasic.PROFILE_BASIC.NATIONALITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return ProfileBasic.PROFILE_BASIC.LOCATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field6() {
		return ProfileBasic.PROFILE_BASIC.BIRTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return ProfileBasic.PROFILE_BASIC.WEIXIN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field8() {
		return ProfileBasic.PROFILE_BASIC.QQ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field9() {
		return ProfileBasic.PROFILE_BASIC.MOTTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return ProfileBasic.PROFILE_BASIC.SELF_INTRODUCTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field11() {
		return ProfileBasic.PROFILE_BASIC.CREATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field12() {
		return ProfileBasic.PROFILE_BASIC.UPDATE_TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UInteger value1() {
		return getProfileId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UByte value3() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getNationality();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getLocation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value6() {
		return getBirth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getWeixin();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value8() {
		return getQq();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value9() {
		return getMotto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getSelfIntroduction();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value11() {
		return getCreateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value12() {
		return getUpdateTime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value1(UInteger value) {
		setProfileId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value3(UByte value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value4(Integer value) {
		setNationality(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value5(Integer value) {
		setLocation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value6(Date value) {
		setBirth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value7(String value) {
		setWeixin(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value8(String value) {
		setQq(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value9(String value) {
		setMotto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value10(String value) {
		setSelfIntroduction(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value11(Timestamp value) {
		setCreateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord value12(Timestamp value) {
		setUpdateTime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ProfileBasicRecord values(UInteger value1, String value2, UByte value3, Integer value4, Integer value5, Date value6, String value7, String value8, String value9, String value10, Timestamp value11, Timestamp value12) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ProfileBasicRecord
	 */
	public ProfileBasicRecord() {
		super(ProfileBasic.PROFILE_BASIC);
	}

	/**
	 * Create a detached, initialised ProfileBasicRecord
	 */
	public ProfileBasicRecord(UInteger profileId, String name, UByte gender, Integer nationality, Integer location, Date birth, String weixin, String qq, String motto, String selfIntroduction, Timestamp createTime, Timestamp updateTime) {
		super(ProfileBasic.PROFILE_BASIC);

		setValue(0, profileId);
		setValue(1, name);
		setValue(2, gender);
		setValue(3, nationality);
		setValue(4, location);
		setValue(5, birth);
		setValue(6, weixin);
		setValue(7, qq);
		setValue(8, motto);
		setValue(9, selfIntroduction);
		setValue(10, createTime);
		setValue(11, updateTime);
	}
}
