/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.userdb.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 用户隐私协议状态表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPrivacyRecord implements Serializable {

    private static final long serialVersionUID = 1606581138;

    private Integer   id;
    private Integer   userId;
    private Integer   status;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Byte      version;

    public UserPrivacyRecord() {}

    public UserPrivacyRecord(UserPrivacyRecord value) {
        this.id = value.id;
        this.userId = value.userId;
        this.status = value.status;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.version = value.version;
    }

    public UserPrivacyRecord(
        Integer   id,
        Integer   userId,
        Integer   status,
        Timestamp createTime,
        Timestamp updateTime,
        Byte      version
    ) {
        this.id = id;
        this.userId = userId;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.version = version;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Byte getVersion() {
        return this.version;
    }

    public void setVersion(Byte version) {
        this.version = version;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserPrivacyRecord (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(status);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(version);

        sb.append(")");
        return sb.toString();
    }
}
