/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.thirdpartydb.tables;


import com.moseeker.baseorm.db.thirdpartydb.Keys;
import com.moseeker.baseorm.db.thirdpartydb.Thirdpartydb;
import com.moseeker.baseorm.db.thirdpartydb.tables.records.ThirdpartyAccountCompanyRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 第三方渠道的所属公司名称
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ThirdpartyAccountCompany extends TableImpl<ThirdpartyAccountCompanyRecord> {

    private static final long serialVersionUID = -560175084;

    /**
     * The reference instance of <code>thirdpartydb.thirdparty_account_company</code>
     */
    public static final ThirdpartyAccountCompany THIRDPARTY_ACCOUNT_COMPANY = new ThirdpartyAccountCompany();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ThirdpartyAccountCompanyRecord> getRecordType() {
        return ThirdpartyAccountCompanyRecord.class;
    }

    /**
     * The column <code>thirdpartydb.thirdparty_account_company.id</code>. 主键
     */
    public final TableField<ThirdpartyAccountCompanyRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "主键");

    /**
     * The column <code>thirdpartydb.thirdparty_account_company.account_id</code>. 第三方渠道账号的编号
     */
    public final TableField<ThirdpartyAccountCompanyRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "第三方渠道账号的编号");

    /**
     * The column <code>thirdpartydb.thirdparty_account_company.company_name</code>. 公司名称
     */
    public final TableField<ThirdpartyAccountCompanyRecord, String> COMPANY_NAME = createField("company_name", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "公司名称");

    /**
     * The column <code>thirdpartydb.thirdparty_account_company.create_time</code>. 创建时间
     */
    public final TableField<ThirdpartyAccountCompanyRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>thirdpartydb.thirdparty_account_company.update_time</code>. 注册时间
     */
    public final TableField<ThirdpartyAccountCompanyRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "注册时间");

    /**
     * Create a <code>thirdpartydb.thirdparty_account_company</code> table reference
     */
    public ThirdpartyAccountCompany() {
        this("thirdparty_account_company", null);
    }

    /**
     * Create an aliased <code>thirdpartydb.thirdparty_account_company</code> table reference
     */
    public ThirdpartyAccountCompany(String alias) {
        this(alias, THIRDPARTY_ACCOUNT_COMPANY);
    }

    private ThirdpartyAccountCompany(String alias, Table<ThirdpartyAccountCompanyRecord> aliased) {
        this(alias, aliased, null);
    }

    private ThirdpartyAccountCompany(String alias, Table<ThirdpartyAccountCompanyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "第三方渠道的所属公司名称");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Thirdpartydb.THIRDPARTYDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ThirdpartyAccountCompanyRecord, Integer> getIdentity() {
        return Keys.IDENTITY_THIRDPARTY_ACCOUNT_COMPANY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ThirdpartyAccountCompanyRecord> getPrimaryKey() {
        return Keys.KEY_THIRDPARTY_ACCOUNT_COMPANY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ThirdpartyAccountCompanyRecord>> getKeys() {
        return Arrays.<UniqueKey<ThirdpartyAccountCompanyRecord>>asList(Keys.KEY_THIRDPARTY_ACCOUNT_COMPANY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ThirdpartyAccountCompany as(String alias) {
        return new ThirdpartyAccountCompany(alias, this);
    }

    /**
     * Rename this table
     */
    public ThirdpartyAccountCompany rename(String name) {
        return new ThirdpartyAccountCompany(name, null);
    }
}
