/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.analytics.tables.records;


import com.moseeker.baseorm.db.analytics.tables.RecommendedResumes;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecommendedResumesRecord extends UpdatableRecordImpl<RecommendedResumesRecord> implements Record6<Integer, String, Integer, Byte, Byte, Double> {

    private static final long serialVersionUID = -1321907178;

    /**
     * Setter for <code>analytics.recommended_resumes.jd_id</code>.
     */
    public void setJdId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>analytics.recommended_resumes.jd_id</code>.
     */
    public Integer getJdId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>analytics.recommended_resumes.resume_id</code>.
     */
    public void setResumeId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>analytics.recommended_resumes.resume_id</code>.
     */
    public String getResumeId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>analytics.recommended_resumes.hr_id</code>.
     */
    public void setHrId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>analytics.recommended_resumes.hr_id</code>.
     */
    public Integer getHrId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>analytics.recommended_resumes.liked</code>.
     */
    public void setLiked(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>analytics.recommended_resumes.liked</code>.
     */
    public Byte getLiked() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>analytics.recommended_resumes.viewed</code>.
     */
    public void setViewed(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>analytics.recommended_resumes.viewed</code>.
     */
    public Byte getViewed() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>analytics.recommended_resumes.sim_weight</code>.
     */
    public void setSimWeight(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>analytics.recommended_resumes.sim_weight</code>.
     */
    public Double getSimWeight() {
        return (Double) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Byte, Byte, Double> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Byte, Byte, Double> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RecommendedResumes.RECOMMENDED_RESUMES.JD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RecommendedResumes.RECOMMENDED_RESUMES.RESUME_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RecommendedResumes.RECOMMENDED_RESUMES.HR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return RecommendedResumes.RECOMMENDED_RESUMES.LIKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return RecommendedResumes.RECOMMENDED_RESUMES.VIEWED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return RecommendedResumes.RECOMMENDED_RESUMES.SIM_WEIGHT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getJdId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getResumeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getHrId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getLiked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getViewed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getSimWeight();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecommendedResumesRecord value1(Integer value) {
        setJdId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecommendedResumesRecord value2(String value) {
        setResumeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecommendedResumesRecord value3(Integer value) {
        setHrId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecommendedResumesRecord value4(Byte value) {
        setLiked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecommendedResumesRecord value5(Byte value) {
        setViewed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecommendedResumesRecord value6(Double value) {
        setSimWeight(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecommendedResumesRecord values(Integer value1, String value2, Integer value3, Byte value4, Byte value5, Double value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecommendedResumesRecord
     */
    public RecommendedResumesRecord() {
        super(RecommendedResumes.RECOMMENDED_RESUMES);
    }

    /**
     * Create a detached, initialised RecommendedResumesRecord
     */
    public RecommendedResumesRecord(Integer jdId, String resumeId, Integer hrId, Byte liked, Byte viewed, Double simWeight) {
        super(RecommendedResumes.RECOMMENDED_RESUMES);

        set(0, jdId);
        set(1, resumeId);
        set(2, hrId);
        set(3, liked);
        set(4, viewed);
        set(5, simWeight);
    }
}
