/**
 * This class is generated by jOOQ
 */
package com.moseeker.baseorm.db.analytics.tables.records;


import com.moseeker.baseorm.db.analytics.tables.WebIm;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WebImRecord extends UpdatableRecordImpl<WebImRecord> implements Record6<Integer, Timestamp, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -229548656;

    /**
     * Setter for <code>analytics.web_im.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>analytics.web_im.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>analytics.web_im.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(1, value);
    }

    /**
     * Getter for <code>analytics.web_im.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(1);
    }

    /**
     * Setter for <code>analytics.web_im.hr</code>. 使用IM的HR数量
     */
    public void setHr(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>analytics.web_im.hr</code>. 使用IM的HR数量
     */
    public Integer getHr() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>analytics.web_im.hr_news</code>. HR发送消息数量
     */
    public void setHrNews(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>analytics.web_im.hr_news</code>. HR发送消息数量
     */
    public Integer getHrNews() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>analytics.web_im.candidate</code>. 使用IM的求职者数量
     */
    public void setCandidate(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>analytics.web_im.candidate</code>. 使用IM的求职者数量
     */
    public Integer getCandidate() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>analytics.web_im.candidate_news</code>. 求职者发送的消息数量
     */
    public void setCandidateNews(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>analytics.web_im.candidate_news</code>. 求职者发送的消息数量
     */
    public Integer getCandidateNews() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Timestamp, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return WebIm.WEB_IM.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field2() {
        return WebIm.WEB_IM.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return WebIm.WEB_IM.HR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return WebIm.WEB_IM.HR_NEWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return WebIm.WEB_IM.CANDIDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return WebIm.WEB_IM.CANDIDATE_NEWS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getHr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getHrNews();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getCandidate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCandidateNews();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebImRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebImRecord value2(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebImRecord value3(Integer value) {
        setHr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebImRecord value4(Integer value) {
        setHrNews(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebImRecord value5(Integer value) {
        setCandidate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebImRecord value6(Integer value) {
        setCandidateNews(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WebImRecord values(Integer value1, Timestamp value2, Integer value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WebImRecord
     */
    public WebImRecord() {
        super(WebIm.WEB_IM);
    }

    /**
     * Create a detached, initialised WebImRecord
     */
    public WebImRecord(Integer id, Timestamp createTime, Integer hr, Integer hrNews, Integer candidate, Integer candidateNews) {
        super(WebIm.WEB_IM);

        set(0, id);
        set(1, createTime);
        set(2, hr);
        set(3, hrNews);
        set(4, candidate);
        set(5, candidateNews);
    }
}
