/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.userdb.tables.records;


import com.moseeker.baseorm.db.userdb.tables.UserMenu;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 菜单
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserMenuRecord extends UpdatableRecordImpl<UserMenuRecord> implements Record9<Integer, String, String, String, Byte, Timestamp, String, Timestamp, String> {

    private static final long serialVersionUID = 753183157;

    /**
     * Setter for <code>userdb.user_menu.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>userdb.user_menu.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>userdb.user_menu.menu_name</code>. 菜单名
     */
    public void setMenuName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>userdb.user_menu.menu_name</code>. 菜单名
     */
    public String getMenuName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>userdb.user_menu.menu_desc</code>. 菜单描述
     */
    public void setMenuDesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>userdb.user_menu.menu_desc</code>. 菜单描述
     */
    public String getMenuDesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>userdb.user_menu.ico_url</code>. 菜单ico地址
     */
    public void setIcoUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>userdb.user_menu.ico_url</code>. 菜单ico地址
     */
    public String getIcoUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>userdb.user_menu.menu_order</code>. 菜单顺序
     */
    public void setMenuOrder(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>userdb.user_menu.menu_order</code>. 菜单顺序
     */
    public Byte getMenuOrder() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>userdb.user_menu.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>userdb.user_menu.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>userdb.user_menu.creator</code>. 创建人
     */
    public void setCreator(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>userdb.user_menu.creator</code>. 创建人
     */
    public String getCreator() {
        return (String) get(6);
    }

    /**
     * Setter for <code>userdb.user_menu.update_time</code>. 修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>userdb.user_menu.update_time</code>. 修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>userdb.user_menu.updator</code>. 修改人
     */
    public void setUpdator(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>userdb.user_menu.updator</code>. 修改人
     */
    public String getUpdator() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Byte, Timestamp, String, Timestamp, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, String, Byte, Timestamp, String, Timestamp, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserMenu.USER_MENU.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UserMenu.USER_MENU.MENU_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserMenu.USER_MENU.MENU_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserMenu.USER_MENU.ICO_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return UserMenu.USER_MENU.MENU_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return UserMenu.USER_MENU.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserMenu.USER_MENU.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return UserMenu.USER_MENU.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UserMenu.USER_MENU.UPDATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMenuName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMenuDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIcoUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getMenuOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getUpdator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value2(String value) {
        setMenuName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value3(String value) {
        setMenuDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value4(String value) {
        setIcoUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value5(Byte value) {
        setMenuOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value7(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value8(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord value9(String value) {
        setUpdator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserMenuRecord values(Integer value1, String value2, String value3, String value4, Byte value5, Timestamp value6, String value7, Timestamp value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserMenuRecord
     */
    public UserMenuRecord() {
        super(UserMenu.USER_MENU);
    }

    /**
     * Create a detached, initialised UserMenuRecord
     */
    public UserMenuRecord(Integer id, String menuName, String menuDesc, String icoUrl, Byte menuOrder, Timestamp createTime, String creator, Timestamp updateTime, String updator) {
        super(UserMenu.USER_MENU);

        set(0, id);
        set(1, menuName);
        set(2, menuDesc);
        set(3, icoUrl);
        set(4, menuOrder);
        set(5, createTime);
        set(6, creator);
        set(7, updateTime);
        set(8, updator);
    }
}
