/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.dictdb.tables;


import com.moseeker.baseorm.db.dictdb.Dictdb;
import com.moseeker.baseorm.db.dictdb.Keys;
import com.moseeker.baseorm.db.dictdb.tables.records.DictAlipaycampusJobcategoryBakRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * job_category[校园工作-基础数据-职位类别]
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DictAlipaycampusJobcategoryBak extends TableImpl<DictAlipaycampusJobcategoryBakRecord> {

    private static final long serialVersionUID = -764506025;

    /**
     * The reference instance of <code>dictdb.dict_alipaycampus_jobcategory_bak</code>
     */
    public static final DictAlipaycampusJobcategoryBak DICT_ALIPAYCAMPUS_JOBCATEGORY_BAK = new DictAlipaycampusJobcategoryBak();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DictAlipaycampusJobcategoryBakRecord> getRecordType() {
        return DictAlipaycampusJobcategoryBakRecord.class;
    }

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.id</code>.
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.code</code>. code
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "code");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.parent_code</code>. 上级code
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, String> PARENT_CODE = createField("parent_code", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "上级code");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.name</code>. 名称
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "名称");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.level</code>. 层级
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, Integer> LEVEL = createField("level", org.jooq.impl.SQLDataType.INTEGER, this, "层级");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.is_hot</code>. 是否热门，1热门
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, Integer> IS_HOT = createField("is_hot", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "是否热门，1热门");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.sort</code>. 排序
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, Integer> SORT = createField("sort", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "排序");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.status</code>. 0删除1正常
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "0删除1正常");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.create_time</code>.
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>dictdb.dict_alipaycampus_jobcategory_bak.update_time</code>.
     */
    public final TableField<DictAlipaycampusJobcategoryBakRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>dictdb.dict_alipaycampus_jobcategory_bak</code> table reference
     */
    public DictAlipaycampusJobcategoryBak() {
        this("dict_alipaycampus_jobcategory_bak", null);
    }

    /**
     * Create an aliased <code>dictdb.dict_alipaycampus_jobcategory_bak</code> table reference
     */
    public DictAlipaycampusJobcategoryBak(String alias) {
        this(alias, DICT_ALIPAYCAMPUS_JOBCATEGORY_BAK);
    }

    private DictAlipaycampusJobcategoryBak(String alias, Table<DictAlipaycampusJobcategoryBakRecord> aliased) {
        this(alias, aliased, null);
    }

    private DictAlipaycampusJobcategoryBak(String alias, Table<DictAlipaycampusJobcategoryBakRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "job_category[校园工作-基础数据-职位类别]");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Dictdb.DICTDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DictAlipaycampusJobcategoryBakRecord> getPrimaryKey() {
        return Keys.KEY_DICT_ALIPAYCAMPUS_JOBCATEGORY_BAK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DictAlipaycampusJobcategoryBakRecord>> getKeys() {
        return Arrays.<UniqueKey<DictAlipaycampusJobcategoryBakRecord>>asList(Keys.KEY_DICT_ALIPAYCAMPUS_JOBCATEGORY_BAK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DictAlipaycampusJobcategoryBak as(String alias) {
        return new DictAlipaycampusJobcategoryBak(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DictAlipaycampusJobcategoryBak rename(String name) {
        return new DictAlipaycampusJobcategoryBak(name, null);
    }
}
