/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.talentpooldb.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * 人才库邮件模板表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TalentpoolEmail implements Serializable {

    private static final long serialVersionUID = 315214153;

    private Integer   id;
    private Integer   disable;
    private String    inscribe;
    private String    context;
    private Integer   configId;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Integer   companyId;

    public TalentpoolEmail() {}

    public TalentpoolEmail(TalentpoolEmail value) {
        this.id = value.id;
        this.disable = value.disable;
        this.inscribe = value.inscribe;
        this.context = value.context;
        this.configId = value.configId;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.companyId = value.companyId;
    }

    public TalentpoolEmail(
        Integer   id,
        Integer   disable,
        String    inscribe,
        String    context,
        Integer   configId,
        Timestamp createTime,
        Timestamp updateTime,
        Integer   companyId
    ) {
        this.id = id;
        this.disable = disable;
        this.inscribe = inscribe;
        this.context = context;
        this.configId = configId;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.companyId = companyId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDisable() {
        return this.disable;
    }

    public void setDisable(Integer disable) {
        this.disable = disable;
    }

    public String getInscribe() {
        return this.inscribe;
    }

    public void setInscribe(String inscribe) {
        this.inscribe = inscribe;
    }

    public String getContext() {
        return this.context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    public Integer getConfigId() {
        return this.configId;
    }

    public void setConfigId(Integer configId) {
        this.configId = configId;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TalentpoolEmail (");

        sb.append(id);
        sb.append(", ").append(disable);
        sb.append(", ").append(inscribe);
        sb.append(", ").append(context);
        sb.append(", ").append(configId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(companyId);

        sb.append(")");
        return sb.toString();
    }
}
