/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.hrdb.tables.daos;


import com.moseeker.baseorm.db.hrdb.tables.HrHeadhunterCompany;
import com.moseeker.baseorm.db.hrdb.tables.records.HrHeadhunterCompanyRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 猎头公司表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HrHeadhunterCompanyDao extends DAOImpl<HrHeadhunterCompanyRecord, com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany, Integer> {

    /**
     * Create a new HrHeadhunterCompanyDao without any configuration
     */
    public HrHeadhunterCompanyDao() {
        super(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY, com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany.class);
    }

    /**
     * Create a new HrHeadhunterCompanyDao with an attached configuration
     */
    public HrHeadhunterCompanyDao(Configuration configuration) {
        super(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY, com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany> fetchById(Integer... values) {
        return fetch(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany fetchOneById(Integer value) {
        return fetchOne(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany> fetchByName(String... values) {
        return fetch(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY.NAME, values);
    }

    /**
     * Fetch records that have <code>short_name IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany> fetchByShortName(String... values) {
        return fetch(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY.SHORT_NAME, values);
    }

    /**
     * Fetch records that have <code>company_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany> fetchByCompanyId(Integer... values) {
        return fetch(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY.COMPANY_ID, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany> fetchByCreateTime(Timestamp... values) {
        return fetch(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.hrdb.tables.pojos.HrHeadhunterCompany> fetchByUpdateTime(Timestamp... values) {
        return fetch(HrHeadhunterCompany.HR_HEADHUNTER_COMPANY.UPDATE_TIME, values);
    }
}
