/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.redpacketdb.tables.records;


import com.moseeker.baseorm.db.redpacketdb.tables.RedpacketRedpacketTrigger;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 红包触发记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedpacketRedpacketTriggerRecord extends UpdatableRecordImpl<RedpacketRedpacketTriggerRecord> implements Record6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 922497787;

    /**
     * Setter for <code>redpacketdb.redpacket_redpacket_trigger.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_redpacket_trigger.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_redpacket_trigger.redpacket_log_id</code>. 红包记录编号
     */
    public void setRedpacketLogId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_redpacket_trigger.redpacket_log_id</code>. 红包记录编号
     */
    public Integer getRedpacketLogId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_redpacket_trigger.trigger_user_id</code>. 红包触发人编号
     */
    public void setTriggerUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_redpacket_trigger.trigger_user_id</code>. 红包触发人编号
     */
    public Integer getTriggerUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_redpacket_trigger.activity_id</code>. 红包活动编号
     */
    public void setActivityId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_redpacket_trigger.activity_id</code>. 红包活动编号
     */
    public Integer getActivityId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_redpacket_trigger.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_redpacket_trigger.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_redpacket_trigger.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_redpacket_trigger.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER.REDPACKET_LOG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER.TRIGGER_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER.ACTIVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRedpacketLogId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTriggerUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketRedpacketTriggerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketRedpacketTriggerRecord value2(Integer value) {
        setRedpacketLogId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketRedpacketTriggerRecord value3(Integer value) {
        setTriggerUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketRedpacketTriggerRecord value4(Integer value) {
        setActivityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketRedpacketTriggerRecord value5(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketRedpacketTriggerRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketRedpacketTriggerRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RedpacketRedpacketTriggerRecord
     */
    public RedpacketRedpacketTriggerRecord() {
        super(RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER);
    }

    /**
     * Create a detached, initialised RedpacketRedpacketTriggerRecord
     */
    public RedpacketRedpacketTriggerRecord(Integer id, Integer redpacketLogId, Integer triggerUserId, Integer activityId, Timestamp createTime, Timestamp updateTime) {
        super(RedpacketRedpacketTrigger.REDPACKET_REDPACKET_TRIGGER);

        set(0, id);
        set(1, redpacketLogId);
        set(2, triggerUserId);
        set(3, activityId);
        set(4, createTime);
        set(5, updateTime);
    }
}
