/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.redpacketdb.tables.records;


import com.moseeker.baseorm.db.redpacketdb.tables.RedpacketWxRetryLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 调用微信发放红包接口重试记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedpacketWxRetryLogRecord extends UpdatableRecordImpl<RedpacketWxRetryLogRecord> implements Record9<Integer, Integer, String, String, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2118444582;

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.wx_status_id</code>. 调用微信发放红包功能时所处的状态的编号
     */
    public void setWxStatusId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.wx_status_id</code>. 调用微信发放红包功能时所处的状态的编号
     */
    public Integer getWxStatusId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.params</code>. 微信红包发放接口参数
     */
    public void setParams(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.params</code>. 微信红包发放接口参数
     */
    public String getParams() {
        return (String) get(2);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.return_code</code>. 返回状态码 SUCCESS/FAIL
     */
    public void setReturnCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.return_code</code>. 返回状态码 SUCCESS/FAIL
     */
    public String getReturnCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.return_msg</code>. 返回信息 返回信息，如非空，为错误原因，比如：签名失败，参数格式校验错误
     */
    public void setReturnMsg(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.return_msg</code>. 返回信息 返回信息，如非空，为错误原因，比如：签名失败，参数格式校验错误
     */
    public String getReturnMsg() {
        return (String) get(4);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.err_code</code>. 错误代码
     */
    public void setErrCode(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.err_code</code>. 错误代码
     */
    public String getErrCode() {
        return (String) get(5);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.err_code_des</code>. 错误代码描述
     */
    public void setErrCodeDes(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.err_code_des</code>. 错误代码描述
     */
    public String getErrCodeDes() {
        return (String) get(6);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>redpacketdb.redpacket_wx_retry_log.update_time</code>. 更新时间
     */
    public void setUpdateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>redpacketdb.redpacket_wx_retry_log.update_time</code>. 更新时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, String, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.WX_STATUS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.PARAMS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.RETURN_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.RETURN_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.ERR_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.ERR_CODE_DES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getWxStatusId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getParams();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getReturnCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReturnMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getErrCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getErrCodeDes();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value2(Integer value) {
        setWxStatusId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value3(String value) {
        setParams(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value4(String value) {
        setReturnCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value5(String value) {
        setReturnMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value6(String value) {
        setErrCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value7(String value) {
        setErrCodeDes(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value8(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord value9(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RedpacketWxRetryLogRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, String value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RedpacketWxRetryLogRecord
     */
    public RedpacketWxRetryLogRecord() {
        super(RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG);
    }

    /**
     * Create a detached, initialised RedpacketWxRetryLogRecord
     */
    public RedpacketWxRetryLogRecord(Integer id, Integer wxStatusId, String params, String returnCode, String returnMsg, String errCode, String errCodeDes, Timestamp createTime, Timestamp updateTime) {
        super(RedpacketWxRetryLog.REDPACKET_WX_RETRY_LOG);

        set(0, id);
        set(1, wxStatusId);
        set(2, params);
        set(3, returnCode);
        set(4, returnMsg);
        set(5, errCode);
        set(6, errCodeDes);
        set(7, createTime);
        set(8, updateTime);
    }
}
