/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.talentpooldb.tables;


import com.moseeker.baseorm.db.talentpooldb.Keys;
import com.moseeker.baseorm.db.talentpooldb.Talentpooldb;
import com.moseeker.baseorm.db.talentpooldb.tables.records.TalentpoolUploadRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * 人才库简历上传记录表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TalentpoolUpload extends TableImpl<TalentpoolUploadRecord> {

    private static final long serialVersionUID = 137188591;

    /**
     * The reference instance of <code>talentpooldb.talentpool_upload</code>
     */
    public static final TalentpoolUpload TALENTPOOL_UPLOAD = new TalentpoolUpload();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TalentpoolUploadRecord> getRecordType() {
        return TalentpoolUploadRecord.class;
    }

    /**
     * The column <code>talentpooldb.talentpool_upload.id</code>.
     */
    public final TableField<TalentpoolUploadRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>talentpooldb.talentpool_upload.file_name</code>. 文件名称
     */
    public final TableField<TalentpoolUploadRecord, String> FILE_NAME = createField("file_name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "文件名称");

    /**
     * The column <code>talentpooldb.talentpool_upload.hr_id</code>.
     */
    public final TableField<TalentpoolUploadRecord, Integer> HR_ID = createField("hr_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>talentpooldb.talentpool_upload.company_id</code>. 公司id
     */
    public final TableField<TalentpoolUploadRecord, Integer> COMPANY_ID = createField("company_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "公司id");

    /**
     * The column <code>talentpooldb.talentpool_upload.create_time</code>.
     */
    public final TableField<TalentpoolUploadRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>talentpooldb.talentpool_upload.update_time</code>. 更新时间
     */
    public final TableField<TalentpoolUploadRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * Create a <code>talentpooldb.talentpool_upload</code> table reference
     */
    public TalentpoolUpload() {
        this("talentpool_upload", null);
    }

    /**
     * Create an aliased <code>talentpooldb.talentpool_upload</code> table reference
     */
    public TalentpoolUpload(String alias) {
        this(alias, TALENTPOOL_UPLOAD);
    }

    private TalentpoolUpload(String alias, Table<TalentpoolUploadRecord> aliased) {
        this(alias, aliased, null);
    }

    private TalentpoolUpload(String alias, Table<TalentpoolUploadRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "人才库简历上传记录表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talentpooldb.TALENTPOOLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TalentpoolUploadRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TALENTPOOL_UPLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TalentpoolUploadRecord> getPrimaryKey() {
        return Keys.KEY_TALENTPOOL_UPLOAD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TalentpoolUploadRecord>> getKeys() {
        return Arrays.<UniqueKey<TalentpoolUploadRecord>>asList(Keys.KEY_TALENTPOOL_UPLOAD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TalentpoolUpload as(String alias) {
        return new TalentpoolUpload(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TalentpoolUpload rename(String name) {
        return new TalentpoolUpload(name, null);
    }
}
