/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.talentpooldb.tables;


import com.moseeker.baseorm.db.talentpooldb.Keys;
import com.moseeker.baseorm.db.talentpooldb.Talentpooldb;
import com.moseeker.baseorm.db.talentpooldb.tables.records.TalentpoolHrAutomaticTagUserRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * hr自动标签和人才关系表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TalentpoolHrAutomaticTagUser extends TableImpl<TalentpoolHrAutomaticTagUserRecord> {

    private static final long serialVersionUID = 1062543221;

    /**
     * The reference instance of <code>talentpooldb.talentpool_hr_automatic_tag_user</code>
     */
    public static final TalentpoolHrAutomaticTagUser TALENTPOOL_HR_AUTOMATIC_TAG_USER = new TalentpoolHrAutomaticTagUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TalentpoolHrAutomaticTagUserRecord> getRecordType() {
        return TalentpoolHrAutomaticTagUserRecord.class;
    }

    /**
     * The column <code>talentpooldb.talentpool_hr_automatic_tag_user.tag_id</code>. 公司标签id
     */
    public final TableField<TalentpoolHrAutomaticTagUserRecord, Integer> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "公司标签id");

    /**
     * The column <code>talentpooldb.talentpool_hr_automatic_tag_user.user_id</code>. 人才id
     */
    public final TableField<TalentpoolHrAutomaticTagUserRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "人才id");

    /**
     * Create a <code>talentpooldb.talentpool_hr_automatic_tag_user</code> table reference
     */
    public TalentpoolHrAutomaticTagUser() {
        this("talentpool_hr_automatic_tag_user", null);
    }

    /**
     * Create an aliased <code>talentpooldb.talentpool_hr_automatic_tag_user</code> table reference
     */
    public TalentpoolHrAutomaticTagUser(String alias) {
        this(alias, TALENTPOOL_HR_AUTOMATIC_TAG_USER);
    }

    private TalentpoolHrAutomaticTagUser(String alias, Table<TalentpoolHrAutomaticTagUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private TalentpoolHrAutomaticTagUser(String alias, Table<TalentpoolHrAutomaticTagUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "hr自动标签和人才关系表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Talentpooldb.TALENTPOOLDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TalentpoolHrAutomaticTagUserRecord>> getKeys() {
        return Arrays.<UniqueKey<TalentpoolHrAutomaticTagUserRecord>>asList(Keys.KEY_TALENTPOOL_HR_AUTOMATIC_TAG_USER_PID_FID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TalentpoolHrAutomaticTagUser as(String alias) {
        return new TalentpoolHrAutomaticTagUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TalentpoolHrAutomaticTagUser rename(String name) {
        return new TalentpoolHrAutomaticTagUser(name, null);
    }
}
