/**
 * This class is generated by jOOQ
 */
package com.moseeker.db.dqv4.tables.records;


import com.moseeker.db.dqv4.tables.UserSettings;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * 用户设置表
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSettingsRecord extends TableRecordImpl<UserSettingsRecord> implements Record4<Integer, Integer, String, String> {

	private static final long serialVersionUID = 1620934652;

	/**
	 * Setter for <code>dqv4.user_settings.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>dqv4.user_settings.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>dqv4.user_settings.user_id</code>. 用户id
	 */
	public void setUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>dqv4.user_settings.user_id</code>. 用户id
	 */
	public Integer getUserId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>dqv4.user_settings.banner_url</code>. profile banner 的qiniu 相对url
	 */
	public void setBannerUrl(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>dqv4.user_settings.banner_url</code>. profile banner 的qiniu 相对url
	 */
	public String getBannerUrl() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>dqv4.user_settings.motto</code>. 个性签名
	 */
	public void setMotto(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>dqv4.user_settings.motto</code>. 个性签名
	 */
	public String getMotto() {
		return (String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, String> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, String> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return UserSettings.USER_SETTINGS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return UserSettings.USER_SETTINGS.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return UserSettings.USER_SETTINGS.BANNER_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return UserSettings.USER_SETTINGS.MOTTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getBannerUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getMotto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserSettingsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserSettingsRecord value2(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserSettingsRecord value3(String value) {
		setBannerUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserSettingsRecord value4(String value) {
		setMotto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserSettingsRecord values(Integer value1, Integer value2, String value3, String value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserSettingsRecord
	 */
	public UserSettingsRecord() {
		super(UserSettings.USER_SETTINGS);
	}

	/**
	 * Create a detached, initialised UserSettingsRecord
	 */
	public UserSettingsRecord(Integer id, Integer userId, String bannerUrl, String motto) {
		super(UserSettings.USER_SETTINGS);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, bannerUrl);
		setValue(3, motto);
	}
}
