/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.referraldb.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferralCompanyConf implements Serializable {

    private static final long serialVersionUID = -1329936901;

    private Integer   id;
    private Integer   companyId;
    private Byte      positionPointsFlag;
    private Timestamp createTime;
    private Timestamp updateTime;
    private Byte      referralKeyInformation;

    public ReferralCompanyConf() {}

    public ReferralCompanyConf(ReferralCompanyConf value) {
        this.id = value.id;
        this.companyId = value.companyId;
        this.positionPointsFlag = value.positionPointsFlag;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
        this.referralKeyInformation = value.referralKeyInformation;
    }

    public ReferralCompanyConf(
        Integer   id,
        Integer   companyId,
        Byte      positionPointsFlag,
        Timestamp createTime,
        Timestamp updateTime,
        Byte      referralKeyInformation
    ) {
        this.id = id;
        this.companyId = companyId;
        this.positionPointsFlag = positionPointsFlag;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.referralKeyInformation = referralKeyInformation;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Byte getPositionPointsFlag() {
        return this.positionPointsFlag;
    }

    public void setPositionPointsFlag(Byte positionPointsFlag) {
        this.positionPointsFlag = positionPointsFlag;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    public Byte getReferralKeyInformation() {
        return this.referralKeyInformation;
    }

    public void setReferralKeyInformation(Byte referralKeyInformation) {
        this.referralKeyInformation = referralKeyInformation;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReferralCompanyConf (");

        sb.append(id);
        sb.append(", ").append(companyId);
        sb.append(", ").append(positionPointsFlag);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(referralKeyInformation);

        sb.append(")");
        return sb.toString();
    }
}
