/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.referraldb.tables.daos;


import com.moseeker.baseorm.db.referraldb.tables.EmployeeReferralRecord;
import com.moseeker.baseorm.db.referraldb.tables.records.EmployeeReferralRecordRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 员工内推记录
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeReferralRecordDao extends DAOImpl<EmployeeReferralRecordRecord, com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord, Integer> {

    /**
     * Create a new EmployeeReferralRecordDao without any configuration
     */
    public EmployeeReferralRecordDao() {
        super(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD, com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord.class);
    }

    /**
     * Create a new EmployeeReferralRecordDao with an attached configuration
     */
    public EmployeeReferralRecordDao(Configuration configuration) {
        super(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD, com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord> fetchById(Integer... values) {
        return fetch(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord fetchOneById(Integer value) {
        return fetchOne(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.ID, value);
    }

    /**
     * Fetch records that have <code>employee IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord> fetchByEmployee(Integer... values) {
        return fetch(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.EMPLOYEE, values);
    }

    /**
     * Fetch records that have <code>position IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord> fetchByPosition(Integer... values) {
        return fetch(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.POSITION, values);
    }

    /**
     * Fetch records that have <code>user IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord> fetchByUser(Integer... values) {
        return fetch(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.USER, values);
    }

    /**
     * Fetch records that have <code>recommend_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord> fetchByRecommendTime(Timestamp... values) {
        return fetch(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.RECOMMEND_TIME, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord> fetchByCreateTime(Timestamp... values) {
        return fetch(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.EmployeeReferralRecord> fetchByUpdateTime(Timestamp... values) {
        return fetch(EmployeeReferralRecord.EMPLOYEE_REFERRAL_RECORD.UPDATE_TIME, values);
    }
}
