/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.referraldb.tables.daos;


import com.moseeker.baseorm.db.referraldb.tables.ReferralPositionBonus;
import com.moseeker.baseorm.db.referraldb.tables.records.ReferralPositionBonusRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReferralPositionBonusDao extends DAOImpl<ReferralPositionBonusRecord, com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus, Integer> {

    /**
     * Create a new ReferralPositionBonusDao without any configuration
     */
    public ReferralPositionBonusDao() {
        super(ReferralPositionBonus.REFERRAL_POSITION_BONUS, com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus.class);
    }

    /**
     * Create a new ReferralPositionBonusDao with an attached configuration
     */
    public ReferralPositionBonusDao(Configuration configuration) {
        super(ReferralPositionBonus.REFERRAL_POSITION_BONUS, com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus> fetchById(Integer... values) {
        return fetch(ReferralPositionBonus.REFERRAL_POSITION_BONUS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus fetchOneById(Integer value) {
        return fetchOne(ReferralPositionBonus.REFERRAL_POSITION_BONUS.ID, value);
    }

    /**
     * Fetch records that have <code>position_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus> fetchByPositionId(Integer... values) {
        return fetch(ReferralPositionBonus.REFERRAL_POSITION_BONUS.POSITION_ID, values);
    }

    /**
     * Fetch records that have <code>total_bonus IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus> fetchByTotalBonus(Integer... values) {
        return fetch(ReferralPositionBonus.REFERRAL_POSITION_BONUS.TOTAL_BONUS, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus> fetchByCreateTime(Timestamp... values) {
        return fetch(ReferralPositionBonus.REFERRAL_POSITION_BONUS.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.referraldb.tables.pojos.ReferralPositionBonus> fetchByUpdateTime(Timestamp... values) {
        return fetch(ReferralPositionBonus.REFERRAL_POSITION_BONUS.UPDATE_TIME, values);
    }
}
