/*
 * This file is generated by jOOQ.
*/
package com.moseeker.baseorm.db.profiledb.tables.daos;


import com.moseeker.baseorm.db.profiledb.tables.ProfileBasic;
import com.moseeker.baseorm.db.profiledb.tables.records.ProfileBasicRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * 用户profile基础个人信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfileBasicDao extends DAOImpl<ProfileBasicRecord, com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic, Integer> {

    /**
     * Create a new ProfileBasicDao without any configuration
     */
    public ProfileBasicDao() {
        super(ProfileBasic.PROFILE_BASIC, com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic.class);
    }

    /**
     * Create a new ProfileBasicDao with an attached configuration
     */
    public ProfileBasicDao(Configuration configuration) {
        super(ProfileBasic.PROFILE_BASIC, com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic object) {
        return object.getProfileId();
    }

    /**
     * Fetch records that have <code>profile_id IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByProfileId(Integer... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.PROFILE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>profile_id = value</code>
     */
    public com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic fetchOneByProfileId(Integer value) {
        return fetchOne(ProfileBasic.PROFILE_BASIC.PROFILE_ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByName(String... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.NAME, values);
    }

    /**
     * Fetch records that have <code>gender IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByGender(Byte... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.GENDER, values);
    }

    /**
     * Fetch records that have <code>nationality_code IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByNationalityCode(Integer... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.NATIONALITY_CODE, values);
    }

    /**
     * Fetch records that have <code>nationality_name IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByNationalityName(String... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.NATIONALITY_NAME, values);
    }

    /**
     * Fetch records that have <code>city_code IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByCityCode(Integer... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.CITY_CODE, values);
    }

    /**
     * Fetch records that have <code>city_name IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByCityName(String... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.CITY_NAME, values);
    }

    /**
     * Fetch records that have <code>birth IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByBirth(Date... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.BIRTH, values);
    }

    /**
     * Fetch records that have <code>weixin IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByWeixin(String... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.WEIXIN, values);
    }

    /**
     * Fetch records that have <code>qq IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByQq(String... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.QQ, values);
    }

    /**
     * Fetch records that have <code>motto IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByMotto(String... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.MOTTO, values);
    }

    /**
     * Fetch records that have <code>self_introduction IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchBySelfIntroduction(String... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.SELF_INTRODUCTION, values);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByCreateTime(Timestamp... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.moseeker.baseorm.db.profiledb.tables.pojos.ProfileBasic> fetchByUpdateTime(Timestamp... values) {
        return fetch(ProfileBasic.PROFILE_BASIC.UPDATE_TIME, values);
    }
}
